[workspace]
resolver = "2"
members = [
  "crates/libs/yarrp",
  "crates/libs/yarrp-openssl",
  "crates/libs/yarrp-rustls",
  "crates/samples/tonic_bin",
  "crates/samples/tonic_openssl_test",
  "crates/samples/tonic_shared",
  "crates/samples/tonic_test",
]

[workspace.dependencies]
cfg-if = "1"
futures = "0.3"
hex = "0.4"
http = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["client"] }
hyper-util = { version = "0.1", default-features = false, features = ["server-auto","tokio", "client-legacy",] }
hyperlocal-with-windows = "0.9"
openssl = { version = "0.10" }
pin-project-lite = "0.2"
prost = "0.14"
prost-build = "0.14"
rustls = { version = "0.23", default-features = false, features = ["std"] }
rustls-cng = { version = "0.7", default-features = false }
rustls-symcrypt = { version = "0.2", default-features = false }
tokio = { version = "1", features = ["full"] }
tokio-openssl = { version = "0.6" }
tokio-rustls = { version = "0.26", default-features = false }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = "0.7"
tonic = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"
tower = { version = "0.5", features = ["util"] }
tracing = { version = "0.1", features = ["log"] }
trait-variant = "0.1"
uds_windows = "1"
x509-parser = "0.18"

# libs in this repo
yarrp = { path = "./crates/libs/yarrp" }
yarrp-rustls = { path = "./crates/libs/yarrp-rustls" }
yarrp-openssl = { path = "./crates/libs/yarrp-openssl" }
# test crates
tonic_test = { path = "./crates/samples/tonic_test" }
tonic_openssl_test = { path = "./crates/samples/tonic_openssl_test" }
tonic_shared = { path = "./crates/samples/tonic_shared" }
