name: build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

env:
  RUST_MSRV: "1.90.0"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      rust-msrv: ${{ env.RUST_MSRV }}
      rust-version: ${{ steps.parse.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: parse
        run: |
          version=$(grep 'channel' rust-toolchain.toml | sed 's/.*"\(.*\)"/\1/')
          echo "version=$version" >> "$GITHUB_OUTPUT"

  build:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        BUILD_TYPE: ["Debug"] # "Release"
        os: [ windows-latest ] # , ubuntu-latest
        rust: [ '${{ needs.setup.outputs.rust-msrv }}', '${{ needs.setup.outputs.rust-version }}' ]
    steps:
    - uses: actions/checkout@v4

    - name: set env symcrypt
      shell: pwsh
      run: echo "SYMCRYPT_LIB_PATH=${PWD}/build/_deps/symcrypt_release-src/dll" >> $env:GITHUB_ENV

    # Use OpenSSL on Windows. It is the ShiningLight.OpenSSL.Dev package.
    - name: Set openssl environment variables
      if: runner.os == 'Windows'
      run: |
        echo "OPENSSL_DIR=C:/Program Files/OpenSSL" >> $env:GITHUB_ENV
        echo "OPENSSL_LIB_DIR=C:/Program Files/OpenSSL/lib/VC/x64/MDd" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy

    - uses: taiki-e/install-action@protoc

    - name: run cmake
      run: >
        cmake . -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -B build

    - name: run build
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }}

    - name: Run cargo check
      run: cargo +${{ matrix.rust }} check

    - name: Run cargo fmt
      run: cargo +${{ matrix.rust }} fmt --all -- --check

    - name: Run cargo clippy
      run: cargo +${{ matrix.rust }} clippy --all-targets -- -D warnings

    - name: run all rust unittests
      run: cargo +${{ matrix.rust }} test --all-targets
